# Generated by Django 5.0.2 on 2024-03-03 21:45

import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators
import payapp.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('balance_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('GBP', 'GBP £'), ('USD', 'USD $')], default='GBP', editable=False, max_length=3)),
                ('balance', payapp.models.PayAppMoneyField(decimal_places=2, default=Decimal('0'), default_currency='GBP', max_digits=11, validators=[djmoney.models.validators.MinMoneyValidator(0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('GBP', 'GBP £'), ('USD', 'USD $')], default='GBP', editable=False, max_length=3)),
                ('amount', payapp.models.PayAppMoneyField(decimal_places=2, default=Decimal('0'), default_currency='GBP', max_digits=11, validators=[djmoney.models.validators.MinMoneyValidator(0)])),
                ('completed', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('by_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_by', to='payapp.person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_to', to='payapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('GBP', 'GBP £'), ('USD', 'USD $')], default='GBP', editable=False, max_length=3)),
                ('amount', payapp.models.PayAppMoneyField(decimal_places=2, default=Decimal('0'), default_currency='GBP', max_digits=11, validators=[djmoney.models.validators.MinMoneyValidator(0)])),
                ('submission_datetime', models.DateTimeField()),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions_from', to='payapp.person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions_to', to='payapp.person')),
            ],
        ),
    ]
